services:
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_e2e:/var/lib/postgresql/data

  redis:
    volumes:
      - redis_data_e2e:/data

  backend:
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  app:
    image: nginx:alpine
    ports:
      - '61234:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

volumes:
  postgres_data_e2e:
  redis_data_e2e:
